name: pinaypal_remote
description: A Flutter remote control app for PinayPal Backup Manager.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^10.4.0
  firebase_core: ^2.24.2
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  http: ^1.2.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
